
package servicecontainer;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "NIMHANSServiceContainerExtra", targetNamespace = "http://ServiceContainer/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface NIMHANSServiceContainerExtra {


    /**
     * 
     * @param inHosId
     * @param inRegNo
     * @param inTokenStr
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPatDetailsByRegno", targetNamespace = "http://ServiceContainer/", className = "servicecontainer.GetPatDetailsByRegno")
    @ResponseWrapper(localName = "getPatDetailsByRegnoResponse", targetNamespace = "http://ServiceContainer/", className = "servicecontainer.GetPatDetailsByRegnoResponse")
    @Action(input = "http://ServiceContainer/NIMHANSServiceContainerExtra/getPatDetailsByRegnoRequest", output = "http://ServiceContainer/NIMHANSServiceContainerExtra/getPatDetailsByRegnoResponse")
    public String getPatDetailsByRegno(
        @WebParam(name = "in_token_str", targetNamespace = "")
        String inTokenStr,
        @WebParam(name = "in_reg_no", targetNamespace = "")
        String inRegNo,
        @WebParam(name = "in_hos_id", targetNamespace = "")
        int inHosId);

    /**
     * 
     * @param inSampleNo
     * @param inTokenStr
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getReportDetailsBySampleNo", targetNamespace = "http://ServiceContainer/", className = "servicecontainer.GetReportDetailsBySampleNo")
    @ResponseWrapper(localName = "getReportDetailsBySampleNoResponse", targetNamespace = "http://ServiceContainer/", className = "servicecontainer.GetReportDetailsBySampleNoResponse")
    @Action(input = "http://ServiceContainer/NIMHANSServiceContainerExtra/getReportDetailsBySampleNoRequest", output = "http://ServiceContainer/NIMHANSServiceContainerExtra/getReportDetailsBySampleNoResponse")
    public String getReportDetailsBySampleNo(
        @WebParam(name = "in_token_str", targetNamespace = "")
        String inTokenStr,
        @WebParam(name = "in_sample_no", targetNamespace = "")
        String inSampleNo);

    /**
     * 
     * @param inSampleNo
     * @param inTokenStr
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUHIDDetailsOfSampleBySampleNo", targetNamespace = "http://ServiceContainer/", className = "servicecontainer.GetUHIDDetailsOfSampleBySampleNo")
    @ResponseWrapper(localName = "getUHIDDetailsOfSampleBySampleNoResponse", targetNamespace = "http://ServiceContainer/", className = "servicecontainer.GetUHIDDetailsOfSampleBySampleNoResponse")
    @Action(input = "http://ServiceContainer/NIMHANSServiceContainerExtra/getUHIDDetailsOfSampleBySampleNoRequest", output = "http://ServiceContainer/NIMHANSServiceContainerExtra/getUHIDDetailsOfSampleBySampleNoResponse")
    public String getUHIDDetailsOfSampleBySampleNo(
        @WebParam(name = "in_token_str", targetNamespace = "")
        String inTokenStr,
        @WebParam(name = "in_sample_no", targetNamespace = "")
        String inSampleNo);

}
