
package servicecontainer;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "NIMHANSServiceContainerExtra", targetNamespace = "http://ServiceContainer/", wsdlLocation = "http://10.11.3.145/portalws/NIMHANSServiceContainerExtra?wsdl")
public class NIMHANSServiceContainerExtra_Service
    extends Service
{

    private final static URL NIMHANSSERVICECONTAINEREXTRA_WSDL_LOCATION;
    private final static WebServiceException NIMHANSSERVICECONTAINEREXTRA_EXCEPTION;
    private final static QName NIMHANSSERVICECONTAINEREXTRA_QNAME = new QName("http://ServiceContainer/", "NIMHANSServiceContainerExtra");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.11.3.145/portalws/NIMHANSServiceContainerExtra?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        NIMHANSSERVICECONTAINEREXTRA_WSDL_LOCATION = url;
        NIMHANSSERVICECONTAINEREXTRA_EXCEPTION = e;
    }

    public NIMHANSServiceContainerExtra_Service() {
        super(__getWsdlLocation(), NIMHANSSERVICECONTAINEREXTRA_QNAME);
    }

    public NIMHANSServiceContainerExtra_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), NIMHANSSERVICECONTAINEREXTRA_QNAME, features);
    }

    public NIMHANSServiceContainerExtra_Service(URL wsdlLocation) {
        super(wsdlLocation, NIMHANSSERVICECONTAINEREXTRA_QNAME);
    }

    public NIMHANSServiceContainerExtra_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, NIMHANSSERVICECONTAINEREXTRA_QNAME, features);
    }

    public NIMHANSServiceContainerExtra_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NIMHANSServiceContainerExtra_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns NIMHANSServiceContainerExtra
     */
    @WebEndpoint(name = "NIMHANSServiceContainerExtraPort")
    public NIMHANSServiceContainerExtra getNIMHANSServiceContainerExtraPort() {
        return super.getPort(new QName("http://ServiceContainer/", "NIMHANSServiceContainerExtraPort"), NIMHANSServiceContainerExtra.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NIMHANSServiceContainerExtra
     */
    @WebEndpoint(name = "NIMHANSServiceContainerExtraPort")
    public NIMHANSServiceContainerExtra getNIMHANSServiceContainerExtraPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ServiceContainer/", "NIMHANSServiceContainerExtraPort"), NIMHANSServiceContainerExtra.class, features);
    }

    private static URL __getWsdlLocation() {
        if (NIMHANSSERVICECONTAINEREXTRA_EXCEPTION!= null) {
            throw NIMHANSSERVICECONTAINEREXTRA_EXCEPTION;
        }
        return NIMHANSSERVICECONTAINEREXTRA_WSDL_LOCATION;
    }

}
